apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadiuqh7182-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadiuqh7182-tenant-component
    app.kubernetes.io/part-of: loadiuqh7182-tenant-app
  name: loadiuqh7182-tenant-component
  namespace: loadiuqh7182-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadiuqh7182-tenant-component
    weight: null
status: {}
