apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadiuqh7182-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadiuqh7182-tenant-component
    app.kubernetes.io/part-of: loadiuqh7182-tenant-app
  name: loadiuqh7182-tenant-component
  namespace: loadiuqh7182-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadiuqh7182-tenant-component
status:
  loadBalancer: {}
